#!/bin/bash

# Author cervigni
# This script creates the pawsey sync crontab and files if they do not exist

## CHECK IF CRONTAB FILE FOR OWNCLOUD EXISTS, IF NOT CREATES IT

if [ ! -e "$HOME/.pawsey-sync-crontab" ]
then
  /usr/bin/crontab -l > $HOME/.pawsey-sync-crontab
  echo 'MAILTO=""' >> $HOME/.pawsey-sync-crontab
  echo "*/5 * * * * $HOME/.pawsey-sync/pawsey-sync" >> $HOME/.pawsey-sync-crontab
  crontab .pawsey-sync-crontab
  echo "- Pawsey Sync activated every 5 minutes..."
fi

## CHECK IF CONFIGURATION FILE EXISTS, if it does not create it
if [ ! -e "$HOME/.pawsey-sync-config" ]
then
  mkdir $HOME/.pawsey-sync
  cat > "$HOME/.pawsey-sync-config" << EOL
#!/bin/bash

# PLEASE READ THE DOCUMENTATION BEFORE ACTIVATING THE PAWSEY SYNC
ACTIVATE_PAWSEY_SYNC=no

# CONFIGURATION OPTIONS
OC_USERNAME=your-pawsey-username-here
OC_DEVICE_TOKEN=device-token-goes-here

# SYiNC OPTIONS
NIMBUS_SYNC_DIRECTORY=/data
SYNC_NIMBUS=no
SYNC_HOME=no
EOL
fi

## CREATE unsync folders file for HOME SYNC only

if [ ! -e "$HOME/.pawsey-sync-unsynced-folders" ]
then
  cat > "$HOME/.pawsey-sync-unsynced-folders" << EOL
## LIST CONTAINING FOLDERS NOT TO SYNC only for home folder
pawsey-sync-group
pawsey-sync-scratch
pawsey-sync-nimbus
EOL
  echo "- Configuration files written. Pawsey Sync installed."
else
  echo "!! Pawsey sync is already installed !!"
fi

echo "IMPORTANT: Please edit the file .pawsey-sync-config to activate syncronization and for further options."



## CHECK IF SYNC FILE FILE EXISTS, if it does not create it
if [ ! -e "$HOME/.pawsey-sync/pawsey-sync" ]
then
  cat > "$HOME/.pawsey-sync/pawsey-sync" << EOL
#!/bin/bash -l

# by cervigni

OC_SERVER=https://nextcloud.pawsey.org.au/remote.php/webdav
OC_USER_HOME=\$HOME
OC_USER_HOME_DIR=\$HOME/pawsey-sync-home

#SOURCE USER MADE CONFIG
source "\$HOME/.pawsey-sync-config"

##ACTIVATE SYNC ONLY IF FLAG FILE EXISTS
if [ "\$ACTIVATE_PAWSEY_SYNC" == "yes" ]; then
  ## pull image regardless (no root access to docker images to check if exists)
  docker pull pawsey/pawsey_owncloud_client
  # IF ACTIVATED - SYNC
  if [ "\$SYNC_HOME" == "yes" ]; then
    if [ ! -d "\$OC_USER_HOME_DIR" ]; then
      mkdir \$OC_USER_HOME_DIR
    fi
    #SYNC HOME DIRECTORY EXCLUDING DIRECTORY BELOW
    docker container run --mount type=bind,source="\$OC_USER_HOME_DIR",target=/ocdata pawsey/pawsey_owncloud_client owncloudcmd --user \$OC_USERNAME --password \$OC_DEVICE_TOKEN --unsyncedfolders /ocdata/.pawsey-sync-unsynced-folders /ocdata \$OC_SERVER
  fi
  if [ "\$SYNC_NIMBUS" == "yes" ]; then
    #CREATE SYNC DIRECTORY IF DOES NOT EXIST
    echo curl -X PROPFIND "\$OC_SERVER/pawsey-sync-nimbus" -k -u \${OC_USERNAME}:\${OC_DEVICE_TOKEN}
    direxist=\`curl -X PROPFIND "\$OC_SERVER/pawsey-sync-nimbus" -k -u \${OC_USERNAME}:\${OC_DEVICE_TOKEN}\`
    if [ -z "\$direxist" ]
    then
      curl -X MKCOL "\$OC_SERVER/pawsey-sync-nimbus" -k -u \${OC_USERNAME}:\${OC_DEVICE_TOKEN}
    fi
    # SYNC ONLY NIMBUS
    docker container run --mount type=bind,source="\$NIMBUS_SYNC_DIRECTORY",target=/ocdata pawsey/pawsey_owncloud_client owncloudcmd --user \$OC_USERNAME --password \$OC_DEVICE_TOKEN /ocdata \$OC_SERVER/pawsey-sync-nimbus
  fi
fi
EOL
  #MAKE SCRIPT EXECUTABLE
  chmod +x $HOME/.pawsey-sync/pawsey-sync
fi
